### ISSUE TITLE
Minus sign error in getEnuLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion

### ISSUE THREAD

**Issue by SamFayolle** [tudat-team/tudat#129]
I believe that there is a small minus sign error here: https://github.com/tudat-team/tudat/blob/a65df7694a34cfff7cb80214154049c55f7a2fb3/src/astro/reference_frames/referenceFrameTransformations.cpp#L578 
I think that it should be pi/2 + latitude and not pi/2 - latitude(?) This actually only affects the ground station state definition (this function is not called anywhere else). It was the cause for some discrepancies w.r.t. JPL Horizons when checking the calculation of the elevation of an object seen by a given ground station.

**Comment by DominicDirkx** [comment]
The definition in the code corresponds to this reference:
https://gssc.esa.int/navipedia//index.php/Transformations_between_ECEF_and_ENU_coordinates
that is referred to in the code, but if you found a discrepancy with Horizons I'm guessing our implementation is wrong, and there's a convention difference somewhere. Do you have an example result from Horizons that we could use for a unit test?

**Comment by MarieFayolle** [comment]
I am sorry, I read through it this morning but very quickly and apparently wrongly. But the tests with Horizons still seem to indicate that there is a minus sign problem somewhere in the GroundStationState class for the latitude (it could still be that it is my setup which is wrong though). I can give you an example with Horizons indeed.

**Comment by DominicDirkx** [comment]
Thanks! It's very well possible that there is an error remaining here, let me know when you have a comparison data point/set :)

**Comment by MarieFayolle** [comment]
So I calculated the elevation of Jupiter at 2023-12-30 00:47:00 UT, from a fictitious ground station with the following geodetic coordinates: 0°E, 60°N, 0 km. The elevation computed by Horizons is equal to 17.4 deg (complete output file attached). [horizons_results.txt](https://github.com/tudat-team/tudat/files/10141961/horizons_results.txt)

In tudat, I got an elevation of -3.95 deg but an elevation of 17.4 deg indeed if I changed the latitude of the station to - 60deg. It could very well be that the issue is on my side, but to be honest I cannot understand it yet.

Again, my apologies in advance if the code in Tudat is correct and the issue comes from my side!

**Comment by DominicDirkx** [comment]
Thanks! Could you copy a code snippet/link to the repo on how you initialize the ground station, and how you compute the elevation in Tudat?

**Comment by MarieFayolle** [comment]
I just added you as a collaborator to my repo and here is the link to the code: https://github.com/MarieFayolle/StellarOccultations/blob/master/observability.cpp

I am sorry, it is a bit messy as I was in debug mode :)

**Comment by DominicDirkx** [comment]
This is quite confusing. I don't have a quick answer for you, but could you also run Horizons with a latitude/longitude that is not so 'neat'? Using 60 and 0 degrees may lead to things getting cancelled out, as their sines/cosines have nice round values. This may lead to your solution of swapping the minus sign *only* working in this specific case.

**Comment by MiguelAvillez** [comment]
> I just added you as a collaborator to my repo and here is the link to the code: https://github.com/MarieFayolle/StellarOccultations/blob/master/observability.cpp
> 
> I am sorry, it is a bit messy as I was in debug mode :)

 
@MarieFayolle Can you also add me to your repo? 😊

**Comment by MiguelAvillez** [comment]
@DominicDirkx Where does this definition of the [azimuth](https://github.com/tudat-team/tudat/blob/9253e18cd66c9296f783c253db031c54ea32d8c8/src/astro/ground_stations/pointingAnglesCalculator.cpp#L35-L44) come from? Shouldn't it be the angle measured clockwise from the north?

**Comment by DominicDirkx** [comment]
No idea. If you think it's wrong or silly, feel free to change it :)

**Comment by MiguelAvillez** [comment]
And any idea what part of this website https://github.com/tudat-team/tudat/blob/9253e18cd66c9296f783c253db031c54ea32d8c8/tests/src/astro/ground_stations/unitTestPointingAnglesCalculator.cpp#L76 was used to generate the data in the test?

**Comment by DominicDirkx** [comment]
Afraid not... This line was added around ~10 years ago (I would guess), and this website may well have changed since then :)

**Comment by MiguelAvillez** [comment]
I modified the definition of azimuth (it is now the angle measured clockwise from the north, as is typical), and unit tested the computation of the azimuth and elevation **from a topocentric vector** (in this branch https://github.com/MiguelAvillez/tudat/tree/feature/azElSignError). 

While the computation of the azimuth from the topocentric vector was wrong (or at least not consistent with the usual definition), the computation of the elevation was correct, so if there is an error in the overall computation of the Az and El it's coming from the conversion of the inertial vector to the topocentric frame. 
Looking at the definition of the frames mention by Dominic (https://github.com/tudat-team/tudat/issues/129#issuecomment-1335303670) and to the used code, I don't see any inconsistency. 
Using the test case Marie listed in https://github.com/tudat-team/tudat/issues/129#issuecomment-1335476567, I get the correct azimuth and elevation if I define the position of the ground station as [long, pi/2 - lat, radius] (Marie mentioned -lat above instead of pi/2 - lat, but I think she had the inertial vector pointing in the wrong direction). Given this pi/2 - lat factor, my guess is that this might be related to some inconsistency in the definition of spherical coordinates: the usual definition of spherical coordinates in tudat is [longitude, **colatitude**, radius] while the spherical coordinates definition used when defining a ground station is [longitude, **latitude**, radius].

As a next step, I would suggest finding some third source that allows unit testing the rotation of an inertial vector to topocentric, and in particular checking that the results obtained via Horizons are indeed correct, and that the values currently used in the test are wrong (my degree of trust in the latter isn't very high...).

**Comment by DominicDirkx** [comment]
Hi @MiguelAvillez, with the changes you've made, I'm able to recreate the Horizons case like a charm! I think the confusion may come from the fact that the spherical position of a ground station does take the latitude (not the co-latitude) in tudat as well. Thanks for figuring out where the issue was!!!
