### ISSUE TITLE
Implicit conversion to Eigen::VectorXd in template argument failing

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#21]
Eigen::VectorXd and Eigen::VectorXd with a specific dimension (e.g. Eigen::Vector6d) are not being implicitly converted in the case of template arguments.

**Comment by DominicDirkx** [comment]
I've added functionality to convert interpolators from Xd to 6d (or vice versa, and the solution will work for any other fixed size, and for matrices too). See below for implementation:

https://github.com/tudat-team/tudat/tree/feature/vector_6d_interpolator_python_fix
https://github.com/tudat-team/tudatpy/tree/feature/vector_6d_interpolator_python_fix

The functionality is not fully unit tested yet, but I've verified that it works with the tabulated ephemeris (due to the implementation, each type of interpolator has a small hard-coded solution in the larger conversion function, so mroe rigorous testing is needed)

**Comment by DominicDirkx** [comment]
I've updated the above branches with a new dedicated unit test. If @MiguelAvillez confirm that the code addresses the problem that they identified, I'll create a pull request for both the tudat and tudatpy code, and merge them into develop

**Comment by MiguelAvillez** [comment]
Everything is working on our side!

**Comment by DominicDirkx** [comment]
Thanks! Code merged :)
