### ISSUE TITLE
Converting LinkEndID, LinkEnds typedefs to class/struct

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat#41]
Make classes / structs out of typedefs. (followup meeting 14.01., API docs observation module).
Will have functional benefits (flexibility in type of LinkeEndID, etc), more homogeneous interface for python users.

input from tudat team, especially new naming, [here](https://tudat.slack.com/archives/C01RW0B4PA8/p1642157175026800)

- [ ] LinkEnds
- [ ] LinkeEndID

- [ ] rename new classes

**Comment by DominicDirkx** [comment]
I've had a first go at seeing what can be done for this, and have come to the following idea for a setup:

- The LinkEndId can be changed into a class without much trouble
- Changing the LinkEnds into a class throughout _all_ of Tudat is quite troublesome. It is used as a key in various maps, and modifying the code such that this is no longer done (or such that our new class can be used as a map key) is rather cumbersome.

So, I propose the following solution:
- We change the LinkEndID into class, which will also permit various ways to make the software more flexible in the future
- We keep the LinkEnds (as map typedef) throughout the backend of the code, but remove it from all the interfaces, and replace it with our own LinkDefinition class. Since the Python interface don't permit the LinkEnds as map/dict key anyway, this does not limit us. For now, I would like to keep this LinkDefinition class simple, and give it a single member: the LinkEnds. we can see if we can extend this in the future, but should make sure that any additional information is then passed on properly to the back-end of the code.

**Comment by DominicDirkx** [comment]
This now implemented in this
https://github.com/tudat-team/tudat/tree/feature/estimate_update
branch. This pull request
https://github.com/tudat-team/tudat/pull/121
lists the open points before merging
