### ISSUE TITLE
Create the tudat C++ API documentation

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#47]
A website similar to the API documentation of [tudatpy.readthedocs.io](https://tudatpy.readthedocs.io/en/latest/index.html) should be created with the API documentation for tudat in C++.

This will require editing all the docstrings that are present in tudat source code, to convert them to regular comments (jo11he can indicate how to do this).

Quite a bit of C++ API documentation is already present in the main docstrings, but it is expected that some cleaning and improvements will be required.

This task should wait at least a couple of weeks for now.

**Comment by jo11he** [comment]
The old c++ Doxygen docstrings follow the following syntax (example for constructor of class)

[permalink](https://github.com/tudat-team/tudat/blob/f31e98620eca202acf528df6b8089e651949a9ff/include/tudat/simulation/estimation_setup/observationSimulationSettings.h#L48)

```
    //! Constructor, defines link end type.
    /*!
     *  Constructor, defines link end type from which observations are to be simulated.
     *  \param linkEndType Link end type from which observations are to be simulated.
     */
```

Now we could either get rid of them entirely (delete the whole block) or simply make them not recognisable to Doxygen anymore. That way they don't interfere with our new way of generating documentation, but we keep the knowledge of the docstrings in the source code, which I think cannot hurt - especially because they mostly contain very good content, i.e. they can (and have already) serve as a basis for the new API docstrings. 

In order to make them un-recognisable to Doxygen, all we have to do is get rid of the "!" characters. A futile version of the block above would look like this:

```
    // Constructor, defines link end type.
    /*
     *  Constructor, defines link end type from which observations are to be simulated.
     *  \param linkEndType Link end type from which observations are to be simulated.
     */
```

This can easily be facilitated by this sequence of bulk-replace operations:
1. //! @get_docstring --> // @get_docstring
2. //!                            --> //
3. /*!                           -- > /*
4. // @get_docstring --> //! @get_docstring

Step 1 and 4 can be skipped if the usual get_docstring call (as our new way of generating documentation) has not been implemented yet (as will be the case for most code that still has potent Doxygen comment blocks).

For adding the "new" docstrings, we add our usual get_docstring call on top of that block.
I.e. this line for the class **description** of the ObservationSimulationSettings class ( Note: I am not sure if this call includes the docs of constructors and member functions, my guess is no, but I don't know the syntax for that yet.)

```
//! @get_docstring(ObservationSimulationSettings.__docstring__)
```

Examples of this practice can be see through the tudat/include/tudat/simulation/environment_setup directory.

**Comment by FilippoOggionni** [comment]
I agree with the workflow proposed by @jo11he and I think we should follow it! As he pointed out, such workflow has already been followed for large parts of both the propagation and environment setup modules.
