### ISSUE TITLE
Incorrect mass propagation setup handling

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#57]
When the mass of a body is propagated, and the `initial_body_masses` list is left empty in `numerical_simulation.propagation_setup.propagator.mass`, an error is printed when the `numerical_simulation.SingleArcSimulator()` function is called. This error is the following:
```
python: /home/jerem/miniconda3/envs/tudat-bundle/include/eigen3/Eigen/src/Core/Block.h:146: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, 1>; int BlockRows = -1; int BlockCols = 1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `startRow >= 0 && blockRows >= 0 && startRow <= xpr.rows() - blockRows && startCol >= 0 && blockCols >= 0 && startCol <= xpr.cols() - blockCols' failed.
Aborted
```
This error is not user-friendly, as it doesn't hint that the mass is simply missing from the inputs, and it is thrown only when the propagation is started rather than during the setup.
I suggest adding a condition when `numerical_simulation.propagation_setup.propagator.mass` is called to verify that the `initial_body_masses` is of the correct length (and its elements of the correct type).

Also, if the `mass_rate_models` are incorrect, the propagation will still work, but the mass will not be propagated and the following warning is printed:
````
Warning when making from-thrust mass-rate model, no thrust model is found; no thust is used
````
I suggest either editing the warning to more explicitly tell the user that the mass will not be propagated, or to be less nice and throw an error so that the user fixes the mass rate models.

**Comment by DominicDirkx** [comment]
Good point, let's make this output better. I can take care of this point, if you've not started it yet. I'll push a solution and ask you to review it,

**Comment by gaffarelj** [comment]
Perfect, I haven't started this yet, I will then let you do it.

**Comment by DominicDirkx** [comment]
I'm writing the corrections to address this issue, and am taking care of a few other similar points as well (will push once all unit tests pass). I came across one point that we need to make a decision on:

* If propagating translational dynamics for body A, but not acceleration models for body A are provided do we:

- Throw an error (safer)
- Automatically create an empy list of acceleration models, and assume that the input is intentional (possibly more user friendly, current implementation)

Perhaps something for a quick discussion on Slack

The inverse check (are acceleration models provided for body X, but do you not propagate body X) now automatically leads to an exception.

The same thing holds for rotation and mass.

**Comment by DominicDirkx** [comment]
Here's the pull request:

https://github.com/tudat-team/tudat/pull/59

For now, the above point I mentioned is addressed as it has been in the past (now made consistent for mass propagation as well). If we want to modify this, I suggest we open a new issue on this

**Comment by gaffarelj** [comment]
Perfect, thank you. I have continued the discussion on Slack, and have approved and executed the pull request.
