### ISSUE TITLE
Very large `.git` history due to old resources from legacy

### ISSUE THREAD

**Issue by geoffreygarrett** [tudat-team/tudat#66]
Perhaps not noticeable in Europe, definitely noticeable in South Africa where I am now, there's a hefty unnecessary ~400 MB in `.git` history. 

[Here's a solution which we can use.](https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-the-git-repository)

![image](https://user-images.githubusercontent.com/26066340/154472061-da55b955-6d1c-4ebc-b82f-9cb87d081792.png)

**Comment by DominicDirkx** [comment]
I'm guessing the reason is that everything that is now in resources used to be inside Tudat itself. Removing all files larger than X MB seems like a decent solution. What would be even better is removing all files of a certain type (e.g. .bsp Spice kernels). It doesn't only have to be one or the other, though

**Comment by geoffreygarrett** [comment]
That sounds like a decent solution, (I don't know the details here) but I don't think the format is in the original storage format. Parts of the history might be compressed. When I have a moment, I'll pursue something in the link I provided.

**Comment by DominicDirkx** [comment]
I checked the file size with the script here:
https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history
And it shows that thee old Tudat/External is to blame for most of the big files. These contents have since been move to Tudat resources.

The ideas in this thread:
https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history
should allow us to remove this directory from the history
